//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gear
    {
        public Gear()
        {
            this.HaulGearXREFs = new HashSet<HaulGearXREF>();
        }
    
        public int GearId { get; set; }
        public string GearNameEnglish { get; set; }
        public string GearNameLocal { get; set; }
    
        public virtual ICollection<HaulGearXREF> HaulGearXREFs { get; set; }
    }
}
