//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isda.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HackathonEntities : DbContext
    {
        public HackathonEntities()
            : base("name=HackathonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gear> Gears { get; set; }
        public DbSet<Haul> Hauls { get; set; }
        public DbSet<HaulGearXREF> HaulGearXREFs { get; set; }
        public DbSet<HaulPhoto> HaulPhotoes { get; set; }
        public DbSet<LandingSite> LandingSites { get; set; }
        public DbSet<Vessel> Vessels { get; set; }
        public DbSet<ViewHaulDetail> ViewHaulDetails { get; set; }
    }
}
