//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haul
    {
        public Haul()
        {
            this.HaulGearXREFs = new HashSet<HaulGearXREF>();
            this.HaulPhotoes = new HashSet<HaulPhoto>();
        }
    
        public int HaulId { get; set; }
        public int LandingSiteId { get; set; }
        public int VesselId { get; set; }
        public System.DateTime SamplingDateTime { get; set; }
        public Nullable<System.DateTime> HaulDateTime { get; set; }
        public Nullable<System.DateTime> TrapSetDateTime { get; set; }
        public int NumberOfFisherman { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public decimal HaulWeight { get; set; }
        public decimal SampleWeight { get; set; }
        public string FishType { get; set; }
    
        public virtual LandingSite LandingSite { get; set; }
        public virtual Vessel Vessel { get; set; }
        public virtual ICollection<HaulGearXREF> HaulGearXREFs { get; set; }
        public virtual ICollection<HaulPhoto> HaulPhotoes { get; set; }
    }
}
