//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingSite
    {
        public LandingSite()
        {
            this.Hauls = new HashSet<Haul>();
        }
    
        public int LandingSiteId { get; set; }
        public string LandingName { get; set; }
        public string BodyOfWater { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
    
        public virtual ICollection<Haul> Hauls { get; set; }
    }
}
