//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public Vessel()
        {
            this.Hauls = new HashSet<Haul>();
        }
    
        public int VesselId { get; set; }
        public string VesselType { get; set; }
        public string Engine { get; set; }
        public string Horsepower { get; set; }
        public Nullable<decimal> BoatLength { get; set; }
        public Nullable<decimal> BoatHeight { get; set; }
        public Nullable<decimal> BoatWidth { get; set; }
    
        public virtual ICollection<Haul> Hauls { get; set; }
    }
}
