//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHaulDetail
    {
        public int GearId { get; set; }
        public string GearNameEnglish { get; set; }
        public string GearNameLocal { get; set; }
        public int HaulGearId { get; set; }
        public int Expr3 { get; set; }
        public string LandingName { get; set; }
        public string BodyOfWater { get; set; }
        public decimal Expr4 { get; set; }
        public decimal Expr5 { get; set; }
    }
}
